### ISSUE TITLE
Unable to download OpenRA files

### ISSUE THREAD

**Issue by brian-cummings** [diddlesnaps/openra#14]
I've been unable to download OpenRA files with Snap revision 1294 (release-20200503) for Raspberry Pi. I keep getting a DNS lookup failure.

**Comment by brian-cummings** [comment]
I figured it out. In the default snapd installation for Raspberry Pi OS, the core snap is not included. Openra didn't have a connection to the network slot.

**Comment by diddledan** [comment]
Thanks for the update. I'm sorry that bit you with little help to find out what's happening. I think this has been filed as a bug against snapd, but I am not certain. It might also be caused by the Raspberry Pi OS version of snapd not automatically updating itself using the core snap like it does on Ubuntu - it's purposely turned off, though I don't know what the reasons for that are.
